service: 8bit-cafe
retain_containers: 2
image: ferdev/8bit-cafe

minimum_version: 2.4.0

deploy_timeout: 600
drain_timeout: 20
readiness_delay: 7

servers:
  web:
    hosts:
      - <%= ENV.fetch("DEPLOY_HOST") %>

ssh:
  user: <%= ENV.fetch("DEPLOY_USER") %>

registry:
  server: ghcr.io
  username: ferdev
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

proxy:
  run:
    bind_ips:
      - 95.216.18.168
      - 2a01:4f9:2a:12c9::2
  hosts:
    - 8bit.cafe
    - www.8bit.cafe
  app_port: 80
  ssl: true
  forward_headers: true
  buffering:
    responses: false
  healthcheck:
    path: /up
    interval: 3
    timeout: 3

logging:
  driver: json-file
  options:
    max-size: 50m
    max-file: "3"
